import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WiseVision",
  description: "Generated by create next app",
  icons: {
    icon: '/images/Logo.svg',
    shortcut: '/images/Logo.svg',
    apple: '/images/Logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} font-outfit h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <ClerkProvider>
          <div className="w-full max-w-[1920px] mx-auto">
            {children}
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
